### ISSUE TITLE
Parameter setting of resnet_v1_152

### ISSUE THREAD

**Issue by wowowoxuan** [hcguoO0/FIA#5]
Hi, thank you for sharing the code! I'm trying to run the attack.py using resnet_v1_152, may I know the parameter setting.

**Comment by hcguoO0** [comment]
As written in our paper,  the drop probability pd = 0.3 (probb=0.7) when attacking normally trained models and pd = 0.1 (probb=0.9) when attacking defense models, and the ensemble number N = 30 (ens=30) in aggregate gradient, and the layer parameter is the last layer of second block for Res-152 (layer_name=resnet_v1_152/block2/unit_8/bottleneck_v1/add)

**Comment by wowowoxuan** [comment]
Got it, thanks a lot!
