### ISSUE TITLE
Hi, there is a issue when I run verify.py

### ISSUE THREAD

**Issue by Aristozhang** [hcguoO0/FIA#6]
(0) Data loss: Unable to open table file ./models_tf/ens3_adv_inception_v3/ens3_adv_inception_v3.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?

the model i use is ens3_adv_incetption_v3, Could you reply me?

**Comment by hcguoO0** [comment]
I don't use a different restore operator,
do you download checkpoint files from https://github.com/tensorflow/models/tree/archive/research/adv_imagenet_models ?
and these are some information about the checkpoint file size, you can check whether something is wrong.
-rw-rw-r-- 1 hcguo hcguo 108728784 Jun 12 14:55 ens3_adv_inception_v3.ckpt.data-00000-of-00001
-rw-rw-r-- 1 hcguo hcguo     17230 Jun 12 14:55 ens3_adv_inception_v3.ckpt.index
-rw-rw-r-- 1 hcguo hcguo   1765911 Jun 12 14:55 ens3_adv_inception_v3.ckpt.meta

**Comment by Aristozhang** [comment]
I have download checkpoint files from the url that you showed, and have tried rename the file name ens3_adv_inception_v3.ckpt.data-00000-of-00001 to ens3_adv_inception_v3.ckpt, there is also a issue, I want to know how you used those files. Thanks!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hcguoO0/FIA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月20日(星期六) 下午4:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hcguoO0/FIA] Hi, there is a issue when I run verify.py (Issue #6)





 
I don't use a different restore operator,
 do you download checkpoint files from https://github.com/tensorflow/models/tree/archive/research/adv_imagenet_models ?
 and these are some information about the checkpoint file size, you can check whether something is wrong.
 -rw-rw-r-- 1 hcguo hcguo 108728784 Jun 12 14:55 ens3_adv_inception_v3.ckpt.data-00000-of-00001
 -rw-rw-r-- 1 hcguo hcguo     17230 Jun 12 14:55 ens3_adv_inception_v3.ckpt.index
 -rw-rw-r-- 1 hcguo hcguo   1765911 Jun 12 14:55 ens3_adv_inception_v3.ckpt.meta
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hcguoO0** [comment]
you don't need to rename the files, you just need to put those 3 files in the folder  ./models_tf/ens3_adv_inception_v3/

**Comment by Aristozhang** [comment]
I did like this firstly, but it didn't work. I found someone have the same problem with me, https://github.com/tensorflow/models/issues/2675
