### ISSUE TITLE
Wondering the exact layer name

### ISSUE THREAD

**Issue by arcus99** [hcguoO0/FIA#7]
Thanks for sharing the code! I've tried to run attack.py on InceptionV3(using layer InceptionV3/InceptionV3/Mixed_5b/concat), InceptionV4(using layer InceptionV4/InceptionV4/Mixed_6f/concat) and Resnet_v1_50(using layer resnet_v1_50/block4/unit_3/bottleneck_v1/conv2/Relu), but got poor results, so could you please share the EXACT LAYER NAME you used to attack?

**Comment by hcguoO0** [comment]
The layer name is  InceptionV3/InceptionV3/Mixed_5b/concat for IneceptionV3 and resnet_v1_50/block2/unit_8/bottleneck_v1/add for Resnet_v1_50. I didn't do experiments on InceptionV4, so I can't give the optimal layer name.
If you still get poor results, please check whether other parameters are wrong.
